version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:3000"
    environment:
      - PORT=3000
      - PG_USERNAME=postgres
      - PG_PASSWORD=mysecretpassword
      - PG_DATABASE=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
